# Generated by Django 4.2.3 on 2023-07-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Teacher Name:')),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender:')),
                ('age', models.IntegerField(verbose_name='Age:')),
            ],
        ),
    ]
