# Generated by Django 4.2.3 on 2023-07-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cod', '0003_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='monday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
