# Generated by Django 4.2.3 on 2023-07-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cod', '0004_monday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='monday',
        ),
    ]
